linters-settings:
  depguard:
    rules:
      main:
        files:
          - "*.go"
        allow:
          - $gostd
          - gopkg.in/natefinch/lumberjack.v2
          - github.com/amirhossein-jamali/journey-hub
          - github.com/fsnotify/fsnotify 
          - github.com/spf13/viper
          - go.uber.org/zap
          - go.uber.org/zap/zapcore

linters:
  enable:
    - typecheck

issues:
  max-same-issues: 50 